#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.
obj-y	+=  mstar_drv_sprd.o
obj-y	+=  mstar_drv_common.o
obj-y	+=  mstar_drv_ic_fw_porting_layer.o
obj-y	+=  mstar_drv_main.o
#obj-y	+=  mstar_drv_mutual_fw_control.o
#obj-y	+=  mstar_drv_mutual_mp_test.o
obj-y	+=  mstar_drv_platform_interface.o
obj-y	+=  mstar_drv_platform_porting_layer.o
obj-y	+=  mstar_drv_self_fw_control.o
obj-y	+=  mstar_drv_self_mp_test.o
obj-y	+=  mstar_drv_utility_adaption.o

